/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/houses/add': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['addHouse'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/houses': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getHouses'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        House: {
            id?: string;
            name?: string;
            locationCords?: string;
            locationName?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            rating?: number;
            userId?: string;
            publishingDate?: string;
            description?: string;
            reviews?: components['schemas']['HouseReview'][];
            rooms?: components['schemas']['HouseRoom'][];
        };
        HouseReview: {
            userId?: string;
            userName?: string;
            rating?: components['schemas']['ReviewRating'];
            review?: string;
        };
        HouseRoom: {
            name?: string;
            description?: string;
            /** @enum {string} */
            roomType?: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVINGROOM';
        };
        ReviewRating: {
            /** Format: int32 */
            overall?: number;
            /** Format: int32 */
            communication?: number;
            /** Format: int32 */
            location?: number;
            /** Format: int32 */
            value?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    addHouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['House'];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': string;
                };
            };
        };
    };
    getHouses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['House'][];
                };
            };
        };
    };
}
